package escrow

import (
	"context"
	"fmt"
	"sync"

	"github.com/willvar/dofs"
)

// ServerMaster is the custodial implementation of the custody axis: the
// deployment holds one 32-byte master key and can therefore unwrap every
// subject key and, through it, every DEK.
//
// A subject key is an application-level key-encryption key such as a per-user
// KEK or a per-namespace KEK. Subject keys are generated by
// the master and persisted only in wrapped form. Per-object DEKs are wrapped
// under a subject key with WrapDEK/UnwrapDEK; that layer does not need the
// master key.
//
// ServerMaster owns its own copy of the master key and clears it on Close.
// Callers must not retain the byte slice passed to NewServerMaster.
type ServerMaster struct {
	mu     sync.RWMutex
	master []byte
}

// NewServerMaster takes ownership of a copy of the 32-byte master key.
func NewServerMaster(master []byte) (*ServerMaster, error) {
	if len(master) != dofs.KeySize {
		return nil, fmt.Errorf("%w: got %d bytes", ErrInvalidKey, len(master))
	}
	return &ServerMaster{master: append([]byte(nil), master...)}, nil
}

// NewServerMasterFromSecret builds a ServerMaster from a hex-encoded
// deployment secret (see ServerKeyFromSecret).
func NewServerMasterFromSecret(secret string) (*ServerMaster, error) {
	master, err := ServerKeyFromSecret(secret)
	if err != nil {
		return nil, err
	}
	return NewServerMaster(master)
}

// GenerateSubjectKey creates a fresh 32-byte subject key (KEK). The caller is
// responsible for wrapping it with WrapSubjectKey before persistence and for
// clearing the returned slice once it is no longer needed in memory.
func (m *ServerMaster) GenerateSubjectKey() ([]byte, error) {
	return dofs.GenerateKey()
}

// WrapSubjectKey wraps a subject key under the master key for persistence.
// The output envelope is [12-byte nonce | ciphertext + 16-byte tag].
func (m *ServerMaster) WrapSubjectKey(subjectKey []byte) ([]byte, error) {
	if len(subjectKey) != dofs.KeySize {
		return nil, fmt.Errorf("%w: subject key got %d bytes", ErrInvalidKey, len(subjectKey))
	}
	m.mu.RLock()
	defer m.mu.RUnlock()
	if len(m.master) != dofs.KeySize {
		return nil, ErrClosed
	}
	wrapped, err := dofs.WrapKey(m.master, subjectKey)
	if err != nil {
		return nil, fmt.Errorf("wrap subject key: %w", err)
	}
	return wrapped, nil
}

// UnwrapSubjectKey recovers a subject key from its envelope using the master
// key. The caller is responsible for clearing the returned key.
func (m *ServerMaster) UnwrapSubjectKey(wrapped []byte) ([]byte, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if len(m.master) != dofs.KeySize {
		return nil, ErrClosed
	}
	if len(wrapped) < dofs.NonceSize+dofs.TagSize+dofs.KeySize {
		return nil, fmt.Errorf("%w: got %d bytes", ErrWrappedKeyShort, len(wrapped))
	}
	subjectKey, err := dofs.UnwrapKey(m.master, wrapped)
	if err != nil {
		return nil, fmt.Errorf("unwrap subject key: %w", err)
	}
	if len(subjectKey) != dofs.KeySize {
		dofs.Clear(subjectKey)
		return nil, ErrInvalidEnvelope
	}
	return subjectKey, nil
}

// UnwrapNamespaceKey implements dofs.KeyProvider so that a ServerMaster can
// back a DOFS metadata store directly: namespace KEK envelopes are subject
// key envelopes wrapped under the same master key. The caller is responsible
// for clearing the returned key.
func (m *ServerMaster) UnwrapNamespaceKey(_ context.Context, namespace dofs.Namespace) ([]byte, error) {
	if m == nil {
		return nil, ErrClosed
	}
	key, err := m.UnwrapSubjectKey(namespace.WrappedKEK)
	if err != nil {
		return nil, fmt.Errorf("unwrap namespace %s key: %w", namespace.ID, err)
	}
	return key, nil
}

// Close clears the in-memory master key. The ServerMaster cannot be reused.
func (m *ServerMaster) Close() {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.master == nil {
		return
	}
	dofs.Clear(m.master)
	m.master = nil
}
